### ISSUE TITLE
babel-loader throws an error when using the library with webpack

### ISSUE THREAD

**Issue by chemjournal** [moroshko/react-autosuggest#150]
I'm using your library along with web pack, and the babel loader and i get this error when web pack compiles. Any idea ?

ERROR in ./~/section-iterator/dist/sectionIterator.js
Module build failed: ReferenceError: [BABEL] /Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/section-iterator/dist/sectionIterator.js: Using removed Babel 5 option: /Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/section-iterator/.babelrc.stage - Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-core/lib/transformation/file/logger.js:39:11)
    at OptionManager.mergeOptions (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:20)
    at OptionManager.addConfig (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
    at OptionManager.init (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-core/lib/transformation/file/options/option-manager.js:461:12)
    at File.initOptions (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-core/lib/transformation/file/index.js:123:22)
    at Pipeline.transform (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-core/lib/transformation/pipeline.js:45:16)
    at transpile (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/salmanhasratkhan/Documents/Projects/react/proreact/aircheap/node_modules/babel-loader/index.js:88:12)
 @ ./~/react-autowhatever/dist/Autowhatever.js 59:23-50

**Comment by moroshko** [comment]
Looks like [this is the issue](https://github.com/moroshko/section-iterator/pull/1). I'll have a look.

**Comment by moroshko** [comment]
Fixed in [3.7.1](https://github.com/moroshko/react-autosuggest/releases/tag/v3.7.1)

**Comment by chemjournal** [comment]
awesome! Thank you
