### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by FakhruddinAbdi** [moroshko/react-autosuggest#282]
I keep seeing the following error 

Can anyone help me to fix it 
```
Uncaught TypeError: Cannot read property 'length' of undefined
    at shallowEqualArrays (http://localhost:8080/bundle.js:48958:18)
    at Autosuggest.componentWillReceiveProps (http://localhost:8080/bundle.js:47934:33)
    at http://localhost:8080/bundle.js:17309:24
    at measureLifeCyclePerf (http://localhost:8080/bundle.js:16775:13)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/bundle.js:17308:10)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:8080/bundle.js:17245:11)
    at Object.receiveComponent (http://localhost:8080/bundle.js:9494:23)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:8080/bundle.js:17452:24)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:8080/bundle.js:17422:11)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:8080/bundle.js:17343:13)
```

**Comment by moroshko** [comment]
@FakhruddinAbdi Could you create a Codepen that demonstrates the issue? You could start from [this one](http://codepen.io/moroshko/pen/LGNJMy).

**Comment by FakhruddinAbdi** [comment]
@markdalgleish this issue solved by looking at this pen : [Async example ](http://codepen.io/moroshko/pen/EPZpev?editors=0010)

Thanks.

**Comment by T620** [comment]
Can you please explain why this solves the issue?

I have the same issue, but following the generic structure in the readme.

**Comment by ashpreetbedi** [comment]
@T620 were you able to figure this out? I'm having the same issue :(

**Comment by ashpreetbedi** [comment]
This is what fixed it for me:
```
function renderSuggestion(suggestion) {
  return (
    <span>{suggestion.name}</span>
  );
}```

I guess needed to render in a <span>
